apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: final
data:
  APP_COLOR: "pink"
  AWS_REGION: "us-east-1"
  MY_NAME: "MD Abu Sayeed | RAZA"
  BG_IMAGE_URL: "s3://clo835-finalproject-711113761458/bg-image.jpg"
  DBHOST: "mysql"
  DBPORT: "3306"
  DATABASE: "employees"