apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: final
data:
  APP_COLOR: "pink"
  AWS_REGION: "us-east-1"
  MY_NAME: "Md Abu Sayeed"
  BG_IMAGE_URL: "s3://your-private-s3-bucket/background.jpg"
  DBHOST: "mysql"
  DBPORT: "3306"
  DATABASE: "employees"